const STORAGE_KEY='training-app-v1';
const LEGACY_STORAGE_KEY='crux-training-v1';
const DATA_VERSION=2;
const iso=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug=s=>String(s).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');

const defaultPlan={
  title:'September 2026',source:'Included plan',importedAt:new Date().toISOString(),
  focus:{'2026-08-29':'Heels down — driving and creating movement through the feet','2026-09-05':'Hips to the wall — moving through those end ranges','2026-09-12':'Knee-in movement — snapping the knee and pushing through the foot','2026-09-19':'Heels down — driving and creating movement through the feet'},
  dayNotes:{'2026-09-01':'1 board climb every 3 minutes for 45 minutes. Aim not to fall, but feel fatigued by the end.','2026-09-03':'1 boulder every minute for 2 sets of 20, with 10 minutes rest.','2026-09-06':'Repeat an 8–10 move boulder with 3 minutes rest. Aim for 6 reps in weeks 1–2.'},
  libraries:{
    fb:{'Jump catches':[{name:'Crimp',detail:'Fast activation: 2 sets elbows in, 2 sets elbows out',sets:'4',reps:'5s',load:'BW',rest:'1 min'},{name:'Pinch',sets:'4',reps:'5s',load:'BW',rest:'1 min'}],FB1:[{name:'1 arm half crimp',detail:'20mm · lift with palm open',sets:'5',reps:'10s',load:'50kg',rest:'3 min'}],FB2:[{name:'Full crimp',detail:'20mm · thumb touching palm',sets:'4',reps:'10s',load:'25kg',rest:'2 min'}]},
    warmup:{'Session warm up 1':[{name:'Scap pulls',sets:'2',reps:'8',load:'BW'},{name:'Scap angels',sets:'2',reps:'6',load:'BW'},{name:'Scap retractions',sets:'2',reps:'6',load:'Banded'}],'Session warm up 2':[{name:'Scap pulls',sets:'2',reps:'8',load:'BW'},{name:'Scap angels',sets:'2',reps:'6',load:'BW'},{name:'Hip flow',sets:'2',reps:'2',load:'BW'},{name:'Lock offs',sets:'2',reps:'30/90/120 · 10s',load:'Start at BW'}]},
    snc:{S1:[{name:'Strict pull up',prescriptions:['5×8','5×8','5×10','5×10','5×12'],load:'BW × 8',rest:'2 min back-to-back'},{name:'Banded shoulder press',prescriptions:['5×8','5×8','5×10','5×10','5×12'],load:'2.5kg × 8'},{name:'Strict TRX Row',prescriptions:['5×8','5×8','5×10','5×10','5×12'],load:'BW × 8',rest:'2 min back-to-back'},{name:'Push up and shoulder tap',prescriptions:['5×8','5×8','5×10','5×10','5×12'],load:'BW × 8'},{name:'Hamstring eccentric',prescriptions:['2×1–2','2×1–2','2×1–2','2×1–2','2×1–2'],rest:'3 min'}],S2:[{name:'External rotation',prescriptions:['3×6','3×6','3×6','3×6','3×6'],load:'0 × 6',rest:'2 min back-to-back'},{name:'Dumbbell IYT pullover holds',prescriptions:['3×10s IEP','3×10s IEP','3×10s IEP','3×10s IEP','3×10s IEP'],load:'2.5kg OES'},{name:'Wide pull up holds',prescriptions:['3×10s','3×10s','3×10s','3×10s','3×10s'],load:'BW',rest:'3 min',detail:'Elbows in, chest high'},{name:'Plank complex',prescriptions:['3×1','3×1','3×1','3×1','3×1'],rest:'1 min',detail:'Dish 30s, superman 30s, plank 60s, side plank 30s OES'}]},
    mobility:{Mobility:['Low lunge','Pigeon','Kneeling hamstring','Achilles stretch','Pancake fold','Frog','Forward fold'].map(name=>({name,reps:'1 min'}))}
  },events:[]
};
function seedEvents(){const start=new Date(2026,8,1),end=new Date(2026,9,2);const byDay={0:['Session warm up 2','FB1','Boulder play','Hard boulder repeats','Mobility'],1:['S1','Mobility'],2:['Session warm up 2','FB1','Project Board','Board volume','Mobility'],3:['Session warm up 1','FB2','Boulder play','S1','Mobility'],4:['Session warm up 1','Boulder volume','Mobility'],5:['S2','Mobility'],6:['Jump catches','Project Board','Mobility']};for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1)){const labels=byDay[d.getDay()]||[];if(labels.length)defaultPlan.events.push({date:iso(d),items:labels.map(label=>({id:slug(label),label,type:classify(label)}))})}}
function classify(label){const s=String(label).trim();if(/^FB\d|jump catches/i.test(s))return'fb';if(/^S\d$/i.test(s))return'snc';if(/warm up/i.test(s))return'warmup';if(/mobility/i.test(s))return'mobility';return'climbing'}
seedEvents();

let state=loadState(),selectedDate=pickInitialDate(),monthCursor=new Date(selectedDate+'T12:00:00'),metric='weight',installPrompt,logDates={snc:selectedDate,fb:selectedDate};
function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||localStorage.getItem(LEGACY_STORAGE_KEY));if(saved?.plan){if((saved.version||1)<DATA_VERSION&&saved.plan.source==='Included plan')saved.plan=structuredClone(defaultPlan);saved.version=DATA_VERSION;saved.scheduleMoves??={};localStorage.setItem(STORAGE_KEY,JSON.stringify(saved));return saved}}catch{}return{version:DATA_VERSION,plan:structuredClone(defaultPlan),done:{},exerciseDone:{},logs:{},scheduleMoves:{}}}
function save(){state.version=DATA_VERSION;localStorage.setItem(STORAGE_KEY,JSON.stringify(state));renderStats()}
function pickInitialDate(){const today=iso(new Date());return state.plan.events.some(e=>e.date===today)?today:(state.plan.events[0]?.date||today)}
function scheduledEvents(){const grouped={};for(const original of state.plan.events){const target=state.scheduleMoves?.[original.date]||original.date,group=grouped[target]??={date:target,items:[],originDates:[]};group.originDates.push(original.date);group.items.push(...original.items.map(item=>target===original.date?item:{...item,originDate:original.date}))}return Object.values(grouped).sort((a,b)=>a.date.localeCompare(b.date))}
function eventFor(date){return scheduledEvents().find(e=>e.date===date)}
function taskKey(date,id){return `${date}|${id}`}
function exerciseKey(date,id,name){return `${date}|${id}|${slug(name)}`}
function getExercises(item){const lib=state.plan.libraries[item.type]||{};return lib[item.label]||[]}
function planWeek(date){const dates=state.plan.events.map(e=>e.date).sort();if(!dates.length)return 1;return Math.floor((new Date(date)-new Date(dates[0]))/604800000)+1}
function focusForDate(date){return Object.entries(state.plan.focus||{}).filter(([start,value])=>value&&start<=date).sort(([a],[b])=>b.localeCompare(a))[0]?.[1]||''}
function weekStart(date){const d=new Date(date+'T12:00:00');d.setDate(d.getDate()-((d.getDay()+6)%7));return d}
function weekDates(date){const start=weekStart(date);return Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d})}
function renderWeekPlanner(){const days=weekDates(selectedDate),start=iso(days[0]),end=iso(days[6]),events=state.plan.events.filter(e=>e.date>=start&&e.date<=end),range=document.querySelector('#weekPlannerRange'),rows=document.querySelector('#weekPlannerRows');range.textContent=`Choose when to complete each session for ${days[0].toLocaleDateString('en-GB',{day:'numeric',month:'short'})} – ${days[6].toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}. Sessions moved to the same day will appear together.`;rows.innerHTML=events.length?events.map(event=>{const original=new Date(event.date+'T12:00:00'),current=state.scheduleMoves?.[event.date]||event.date,summary=[...new Set(event.items.map(item=>labelType(item.type)))].join(', '),options=days.map(day=>{const date=iso(day);return `<option value="${date}" ${date===current?'selected':''}>${day.toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'})}</option>`}).join('');return `<div class="planner-row"><div><strong>${original.toLocaleDateString('en-GB',{weekday:'long'})}'s training</strong><small>${esc(summary)}</small></div><label>Complete on<select data-move-origin="${event.date}">${options}</select></label></div>`}).join(''):'<p class="empty">There are no training sessions in this week.</p>'}

function render(){document.querySelector('#planTitle').textContent=state.plan.title;renderCalendar();renderDay();renderLibrary('snc');renderLibrary('fb');renderProgressOptions();renderProgress();renderStats();renderMeta()}
function renderCalendar(){const root=document.querySelector('#calendar'),y=monthCursor.getFullYear(),m=monthCursor.getMonth();document.querySelector('#calendarHeading').textContent=monthCursor.toLocaleDateString('en-GB',{month:'long',year:'numeric'});let html=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>`<div class="weekday">${x}</div>`).join('');const first=new Date(y,m,1),offset=(first.getDay()+6)%7,start=new Date(y,m,1-offset),mainTypes=['climbing','fb','snc'];for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=iso(d),ev=eventFor(key),groups=mainTypes.filter(type=>ev?.items.some(item=>item.type===type)),segments=groups.map(type=>{const items=ev.items.filter(item=>item.type===type),complete=items.every(item=>state.done[taskKey(item.originDate||key,item.id)]);return `<i class="day-segment segment-${type} ${complete?'complete':''}"></i>`}).join(''),completed=groups.length&&groups.every(type=>ev.items.filter(item=>item.type===type).every(item=>state.done[taskKey(item.originDate||key,item.id)]));html+=`<button class="cal-day ${d.getMonth()!==m?'other ':''}${ev?'has-training ':''}${key===iso(new Date())?'today ':''}${key===selectedDate?'selected ':''}${completed?'done':''}" data-date="${key}" aria-label="${d.toLocaleDateString('en-GB')} ${ev?'training planned':''}">${groups.length?`<span class="day-segments">${segments}</span>`:''}<span class="day-number">${d.getDate()}</span></button>`}root.innerHTML=html;root.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{selectedDate=b.dataset.date;monthCursor=new Date(selectedDate+'T12:00:00');renderCalendar();renderDay()})}
function renderDay(){const root=document.querySelector('#dayPanel'),ev=eventFor(selectedDate),d=new Date(selectedDate+'T12:00:00');let html=`<div class="day-title"><div><span class="eyebrow">${d.toLocaleDateString('en-GB',{weekday:'long'}).toUpperCase()}</span><h2>${d.toLocaleDateString('en-GB',{day:'numeric',month:'long'})}</h2></div><p>Week ${Math.max(1,planWeek(selectedDate))}</p></div>`;const focus=focusForDate(selectedDate),notes=[...new Set((ev?.originDates||[selectedDate]).map(date=>state.plan.dayNotes[date]).filter(Boolean))];if(focus)html+=`<div class="focus-card"><strong>Technique focus</strong><br>${esc(focus)}</div>`;for(const note of notes)html+=`<div class="focus-card"><strong>Session focus</strong><br>${esc(note)}</div>`;if(!ev){root.innerHTML=html+'<div class="chart-card"><p class="empty">No training planned for this day.</p></div>';return}for(const item of ev.items){const completionDate=item.originDate||selectedDate,key=taskKey(completionDate,item.id),ex=getExercises(item),moved=item.originDate?` · moved from ${new Date(item.originDate+'T12:00:00').toLocaleDateString('en-GB',{weekday:'long'})}`:'';html+=`<article class="task-card"><div class="task-head"><input class="check task-check" type="checkbox" data-key="${key}" ${state.done[key]?'checked':''} aria-label="Complete ${esc(item.label)}"><div class="task-copy"><strong>${esc(item.label)}</strong><small>${labelType(item.type)}${ex.length?` · ${ex.length} exercises`:''}${moved}</small></div>${ex.length?`<button class="expand" data-expand="${key}" aria-label="Show exercises">⌄</button>`:''}</div>${ex.length?`<div class="task-details" data-details="${key}">${ex.map(x=>logRow(selectedDate,item,x)).join('')}</div>`:''}</article>`}root.innerHTML=html;wireLogging(root)}
function labelType(t){return({fb:'Fingerboard',snc:'Strength & conditioning',warmup:'Warm-up',mobility:'Mobility',climbing:'Climbing'})[t]||t}
function logRow(date,item,x){const logId=item.originDate?`${item.originDate}-${item.id}`:item.id,k=exerciseKey(date,logId,x.name),log=state.logs[k]||{};return `<div class="log-row"><div class="log-title"><input class="check exercise-check" type="checkbox" data-key="${k}" ${state.exerciseDone[k]?'checked':''} aria-label="Complete ${esc(x.name)}"><span><strong>${esc(x.name)}</strong>${x.detail?` · ${esc(x.detail)}`:''}</span></div><div class="inputs"><label>Weight / load<input data-log="${k}" data-field="weight" value="${esc(log.weight||'')}" placeholder="${esc(x.load||'e.g. 20kg')}"></label><label>Reps / time<input data-log="${k}" data-field="reps" value="${esc(log.reps||'')}" placeholder="${esc(x.reps||x.prescriptions?.[Math.min(4,Math.max(0,planWeek(date)-1))]||'e.g. 8')}"></label></div></div>`}
function wireLogging(root){root.querySelectorAll('.task-check').forEach(x=>x.onchange=()=>{state.done[x.dataset.key]=x.checked;save();renderCalendar()});root.querySelectorAll('.exercise-check').forEach(x=>x.onchange=()=>{state.exerciseDone[x.dataset.key]=x.checked;save()});root.querySelectorAll('[data-log]').forEach(x=>x.onchange=()=>{const k=x.dataset.log;state.logs[k]={...(state.logs[k]||{}),[x.dataset.field]:x.value,updatedAt:new Date().toISOString(),exercise:k.split('|')[2]};save();renderProgressOptions()});root.querySelectorAll('[data-expand]').forEach(x=>x.onclick=()=>{const el=root.querySelector(`[data-details="${CSS.escape(x.dataset.expand)}"]`);el.hidden=!el.hidden;x.textContent=el.hidden?'⌄':'⌃'})}
function renderLibrary(type){const root=document.querySelector(type==='snc'?'#sncSessions':'#fbSessions'),lib=state.plan.libraries[type]||{},date=logDates[type];root.innerHTML=`<div class="library-date"><label>Log date<input type="date" data-library-date="${type}" value="${date}"></label><small>Exercise summaries save automatically</small></div>`+(Object.entries(lib).map(([session,items])=>`<article class="exercise-card"><header><h3>${esc(session)}</h3><span class="pill">${items.length} exercises</span></header>${items.map(x=>`<div class="exercise-line"><strong>${esc(x.name)}</strong><p>${esc(x.detail||'')}${x.rest?`${x.detail?' · ':''}Rest ${esc(x.rest)}`:''}</p><p class="prescription">${esc(type==='snc'?(x.prescriptions||[]).map((p,i)=>`W${i+1} ${p}`).join(' · '):`${x.sets||''} sets · ${x.reps||''} · ${x.load||''}`)}</p>${logRow(date,{id:slug(session),label:session,type},x)}</div>`).join('')}</article>`).join('')||'<div class="chart-card"><p class="empty">No sessions found in this plan.</p></div>');wireLogging(root);root.querySelector('[data-library-date]').onchange=e=>{logDates[type]=e.target.value;renderLibrary(type)}}
function renderStats(){const all=state.plan.events.flatMap(e=>e.items.map(i=>taskKey(e.date,i.id))),done=all.filter(k=>state.done[k]).length;document.querySelector('#completionPct').textContent=all.length?`${Math.round(done/all.length*100)}%`:'0%';const now=new Date(),monday=new Date(now);monday.setDate(now.getDate()-((now.getDay()+6)%7));monday.setHours(0,0,0,0);const scheduled=scheduledEvents(),week=scheduled.filter(e=>{const d=new Date(e.date);return d>=monday&&d<new Date(+monday+7*86400000)}).flatMap(e=>e.items).length;document.querySelector('#weekCount').textContent=week;const days=scheduled.filter(e=>e.items.some(i=>state.done[taskKey(i.originDate||e.date,i.id)])).map(e=>e.date).sort().reverse();let streak=0,cursor=new Date();for(let i=0;i<365;i++){const k=iso(cursor);if(days.includes(k))streak++;else if(i>0)break;cursor.setDate(cursor.getDate()-1)}document.querySelector('#streakCount').textContent=streak}
function logEntries(){return Object.entries(state.logs).filter(([,v])=>v.weight||v.reps).map(([k,v])=>{const [date,,exercise]=k.split('|');return{k,date,exercise,...v}}).sort((a,b)=>a.date.localeCompare(b.date))}
function renderProgressOptions(){const select=document.querySelector('#progressExercise'),current=select.value,ex=[...new Set(logEntries().map(x=>x.exercise))].sort();select.innerHTML=ex.length?ex.map(x=>`<option value="${esc(x)}">${esc(x.replaceAll('-',' '))}</option>`).join(''):'<option>No logged exercises</option>';if(ex.includes(current))select.value=current;select.onchange=renderProgress}
function numeric(s){const m=String(s||'').replace(',','.').match(/-?\d+(\.\d+)?/);return m?Number(m[0]):null}
function renderProgress(){const ex=document.querySelector('#progressExercise').value,entries=logEntries().filter(x=>x.exercise===ex),points=entries.map(x=>({...x,value:numeric(x[metric])})).filter(x=>x.value!==null),chart=document.querySelector('#progressChart');if(points.length<1)chart.innerHTML='<p class="empty">Log an exercise from a training day to see progress here.</p>';else{const vals=points.map(p=>p.value),min=Math.min(...vals),max=Math.max(...vals),range=max-min||1,w=360,h=190,pad=34,coords=points.map((p,i)=>({x:pad+(points.length===1?(w-2*pad)/2:i*(w-2*pad)/(points.length-1)),y:h-pad-(p.value-min)/range*(h-2*pad),...p}));chart.innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(metric)} progress"><line class="chart-grid" x1="${pad}" y1="${pad}" x2="${pad}" y2="${h-pad}"/><line class="chart-grid" x1="${pad}" y1="${h-pad}" x2="${w-pad}" y2="${h-pad}"/><text class="chart-label" x="2" y="${pad+4}">${max}</text><text class="chart-label" x="2" y="${h-pad+4}">${min}</text><polyline class="chart-line" points="${coords.map(p=>`${p.x},${p.y}`).join(' ')}"/>${coords.map(p=>`<circle class="chart-dot" cx="${p.x}" cy="${p.y}" r="5"><title>${p.date}: ${p.value}</title></circle>`).join('')}</svg>`}document.querySelector('#historyList').innerHTML=entries.length?entries.slice().reverse().map(x=>`<div class="history-item"><div><strong>${esc(x.exercise.replaceAll('-',' '))}</strong><p>${new Date(x.date+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}</p></div><strong>${esc(x[metric]||'—')}</strong></div>`).join(''):'<p class="empty">Your exercise history will appear here.</p>'}

function parseWorkbook(wb,source){const names=wb.SheetNames,find=n=>names.find(x=>x.trim().toLowerCase().includes(n));const overview=XLSX.utils.sheet_to_json(wb.Sheets[find('overview')||names[0]],{header:1,raw:true,defval:null});const dateRow=overview.findIndex(r=>r.some(v=>String(v).trim().toLowerCase()==='date'));const focusRow=overview.findIndex(r=>r.some(v=>String(v).trim().toLowerCase()==='tech focus'));const noteRow=overview.findIndex(r=>r.some(v=>String(v).trim().toLowerCase()==='session focus'));const stop=noteRow>dateRow?noteRow:overview.length;const plan={title:'Imported training plan',source,importedAt:new Date().toISOString(),focus:{},dayNotes:{},events:[],libraries:{fb:{},warmup:{},snc:{},mobility:{}}};if(dateRow<0)throw Error('Could not find the Date row on the Overview sheet.');for(let c=0;c<(overview[dateRow]||[]).length;c++){const raw=overview[dateRow][c];let d=raw instanceof Date?raw:(typeof raw==='number'?XLSX.SSF.parse_date_code(raw):null);if(d&&!(d instanceof Date))d=new Date(d.y,d.m-1,d.d);if(!(d instanceof Date)||isNaN(d))continue;const date=iso(d),labels=[];for(let r=dateRow+1;r<stop;r++){const v=overview[r]?.[c];if(typeof v==='string'&&v.trim()&&!['events','training day','tech focus'].includes(v.trim().toLowerCase()))labels.push(v.trim())}const items=[...new Set(labels)].map(label=>({id:slug(label),label,type:classify(label)}));if(items.length)plan.events.push({date,items});if(focusRow>=0&&overview[focusRow]?.[c])plan.focus[date]=String(overview[focusRow][c]);if(noteRow>=0&&overview[noteRow]?.[c])plan.dayNotes[date]=String(overview[noteRow][c])}parseSimple(wb,find('fb'),'fb',plan);parseSimple(wb,find('warm'),'warmup',plan);parseSnc(wb,find('snc'),plan);const dates=plan.events.map(e=>e.date).sort();if(dates.length){const a=new Date(dates[0]+'T12:00:00'),b=new Date(dates.at(-1)+'T12:00:00');plan.title=a.toLocaleDateString('en-GB',{month:'long',year:'numeric'});if(a.getMonth()!==b.getMonth())plan.title+=` – ${b.toLocaleDateString('en-GB',{month:'short'})}`}return plan}
function parseSimple(wb,name,type,plan){if(!name)return;const rows=XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,raw:true,defval:null});let session='';for(let r=4;r<rows.length;r++){const row=rows[r];if(row?.[1])session=String(row[1]).trim();const exercise=type==='fb'?(row?.[2]||row?.[4]):row?.[2];if(!session||!exercise)continue;(plan.libraries[type][session]??=[]).push({name:String(exercise).trim(),detail:type==='fb'?[row?.[3],row?.[4]].filter(Boolean).join(' · '):'',sets:String(row?.[type==='fb'?5:3]??''),reps:String(row?.[type==='fb'?6:4]??''),load:String(row?.[type==='fb'?7:5]??''),rest:String(row?.[type==='fb'?8:6]??'')})}}
function parseSnc(wb,name,plan){if(!name)return;const rows=XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,raw:true,defval:null});let session='';for(let r=5;r<rows.length;r++){const row=rows[r];if(row?.[1])session=String(row[1]).trim();if(!/^S\d/i.test(session)||!row?.[2])continue;(plan.libraries.snc[session]??=[]).push({name:String(row[2]).trim(),detail:String(row[3]||row[15]||''),prescriptions:[row[4],row[6],row[8],row[10],row[12]].map(x=>String(x??'')),load:String(row[5]||''),rest:String(row[14]||'')})}}
async function importBuffer(buffer,source){if(!window.XLSX)throw Error('The spreadsheet reader has not loaded. Check your connection and try again.');const wb=XLSX.read(buffer,{type:'array',cellDates:true});const plan=parseWorkbook(wb,source);if(!plan.events.length)throw Error('No dated sessions were found. Check that the workbook still contains an Overview sheet.');state.plan=plan;state.scheduleMoves={};selectedDate=plan.events[0].date;monthCursor=new Date(selectedDate+'T12:00:00');save();render();toast(`Imported ${plan.events.length} training days`)}
function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2600)}
function renderMeta(){const dates=state.plan.events.map(e=>e.date).sort(),meta=document.querySelector('#planMeta');meta.textContent=`${state.plan.source} · ${dates.length} training days${dates.length?` · ${new Date(dates[0]+'T12:00:00').toLocaleDateString('en-GB')} to ${new Date(dates.at(-1)+'T12:00:00').toLocaleDateString('en-GB')}`:''}`}

document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.bottom-nav button,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#'+b.dataset.view).classList.add('active');scrollTo({top:0,behavior:'smooth'});if(b.dataset.view==='progressView')renderProgress()});
document.querySelector('#prevMonth').onclick=()=>{monthCursor.setMonth(monthCursor.getMonth()-1);renderCalendar()};document.querySelector('#nextMonth').onclick=()=>{monthCursor.setMonth(monthCursor.getMonth()+1);renderCalendar()};
document.querySelector('#arrangeWeek').onclick=()=>{renderWeekPlanner();document.querySelector('#weekPlannerDialog').showModal()};
document.querySelector('#resetWeekPlan').onclick=()=>document.querySelectorAll('[data-move-origin]').forEach(select=>select.value=select.dataset.moveOrigin);
document.querySelector('#saveWeekPlan').onclick=()=>{state.scheduleMoves??={};document.querySelectorAll('[data-move-origin]').forEach(select=>{const origin=select.dataset.moveOrigin;if(select.value===origin)delete state.scheduleMoves[origin];else state.scheduleMoves[origin]=select.value});save();render();document.querySelector('#weekPlannerDialog').close();toast('Week updated')};
document.querySelectorAll('[data-metric]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-metric]').forEach(x=>x.classList.remove('active'));b.classList.add('active');metric=b.dataset.metric;renderProgress()});
document.querySelector('#planFile').onchange=async e=>{try{const f=e.target.files[0];if(f)await importBuffer(await f.arrayBuffer(),f.name)}catch(err){toast(err.message)}};
document.querySelector('#importUrl').onclick=async()=>{try{const value=document.querySelector('#sheetUrl').value,id=value.match(/spreadsheets\/d\/([a-zA-Z0-9-_]+)/)?.[1];if(!id)throw Error('Paste a valid Google Sheets link.');toast('Downloading sheet…');const res=await fetch(`https://docs.google.com/spreadsheets/d/${id}/export?format=xlsx`);if(!res.ok)throw Error('Google could not share this sheet. Check its link access.');await importBuffer(await res.arrayBuffer(),'Google Sheets')}catch(err){toast(err.message||'Direct import failed. Try the Excel upload instead.')}};
document.querySelector('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`training-app-backup-${iso(new Date())}.json`;a.click();URL.revokeObjectURL(a.href)};
document.querySelector('#restoreData').onchange=async e=>{try{const next=JSON.parse(await e.target.files[0].text());if(!next.plan||!next.logs)throw Error('This is not a Training App backup.');next.scheduleMoves??={};state=next;selectedDate=pickInitialDate();monthCursor=new Date(selectedDate+'T12:00:00');save();render();toast('Backup restored')}catch(err){toast(err.message)}};
document.querySelector('#resetPlan').onclick=()=>{if(confirm('Reload the included plan? Your exercise history will be kept.')){state.plan=structuredClone(defaultPlan);state.scheduleMoves={};selectedDate=pickInitialDate();monthCursor=new Date(selectedDate+'T12:00:00');save();render();toast('Included plan restored')}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;document.querySelector('#installBtn').classList.remove('hidden')});document.querySelector('#installBtn').onclick=async()=>{await installPrompt?.prompt();installPrompt=null;document.querySelector('#installBtn').classList.add('hidden')};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
render();
